<?php

namespace App\Http\Controllers;

use Elastic\Elasticsearch\ClientBuilder;

class ElasticController extends Controller
{
    //
    protected $client;

    public function __construct()
    {
        $this->client = ClientBuilder::create()->setHosts([env('ELASTIC_HOST')])->setApiKey(env('ELASTIC_API_KEY'))
            ->build();

    }
    public function test()
    {

        $params = ['index' => 'my_index'];

        $response = $this->client->indices()->create($params);
        dd($response);
    }

    public function index()
    {

        $params = [
            'index' => 'my_index',
            'body' => ['testField' => 'abc'],
        ];

        // Document will be indexed to my_index/_doc/<autogenerated ID>
        $response = $this->client->index($params);
        dd($response);
    }
}
