<?php

namespace App\Http\Controllers;

use Elastic\Elasticsearch\ClientBuilder;

class ElasticController extends Controller
{
    //
    public function test()
    {
        $client = ClientBuilder::create()->setHosts(['https://6b11b46e2f1142e3bd6bd25d809031ba.us-central1.gcp.cloud.es.io:443'])->setApiKey('cHRTZS1wQUJ2bG1BbllJaWh1SnM6U2xKWmpSdXpTX0t6U2QwbXl4M3BHUQ==')
            ->build();

        $params = ['index' => 'my_index'];

        $response = $client->indices()->create($params);
        dd($response);
    }

    public function index()
    {
        $client = ClientBuilder::create()->setHosts(['https://6b11b46e2f1142e3bd6bd25d809031ba.us-central1.gcp.cloud.es.io:443'])->setApiKey('cHRTZS1wQUJ2bG1BbllJaWh1SnM6U2xKWmpSdXpTX0t6U2QwbXl4M3BHUQ==')
            ->build();
        $params = [
            'index' => 'my_index',
            'body' => ['testField' => 'abc'],
        ];

        // Document will be indexed to my_index/_doc/<autogenerated ID>
        $response = $client->index($params);
        dd($response);
    }
}
